### ISSUE TITLE
Derive ORM Entities from io-ts

### ISSUE THREAD

**Issue by mikearnaldi** [mikearnaldi/matechs-effect#105]

**Comment by sledorze** [comment]
@mikearnaldi it's 'complicated', mainly because io-ts are now tag - less.

Actually there's some 'hidden' tags, like this:
https://github.com/gcanti/io-ts/blob/master/src/index.ts#L258

But it is not enforced in the io-ts Type:
https://github.com/gcanti/io-ts/blob/master/src/index.ts#L111

Check for instance:
https://github.com/gcanti/io-ts-types/blob/master/src/DateFromNumber.ts#L20

That's a reason why reflection cannot be used (which is not a bad thing IMHO).
Also, we have no type directed emit in TS so we cannot rely on the compiler to help with that.

Those reasons are why I've started https://github.com/sledorze/morphic-ts
It is usable but lacks some documentation and also a monorepo structure to help scaling with differents technologies.

**Comment by mikearnaldi** [comment]
@sledorze you were refactoring stuff in morphic looks like it might be better to wait and maybe derive the codecs through morphic once stable

**Comment by sledorze** [comment]
@mikearnaldi almost done, the new shape is closer to what would be required when switching to monorepo
I've opened that: https://github.com/sledorze/morphic-ts/issues/3
May try over the next days (never played with annotations programmatically - yet)
That will be a very good addition :)

**Comment by sledorze** [comment]
@mikearnaldi is it still required?

**Comment by mikearnaldi** [comment]
@sledorze I am unsure, in general I am thinking this and graphql in bigger terms ... but still no real concrete ideas
